[unstable]

# recompile the core and compiler_builtins(dependency of core) libraries
build-std = ["core", "compiler_builtins"] 

# enable memset,memcpy... required C library functions in compiler_builtins
build-std-features = ["compiler-builtins-mem"]

# avoid passing the --target parameter on every invocation of cargo build
[build]
target = "x86_64-blog_os.json"


# links the given executable with the project's bootloader dependency
# (added in Cargo.toml)
#  and then launches QEMU
[target.'cfg(target_os = "none")']
runner = "bootimage runner" 